// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: edict.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BestowGazeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EyeId         string                 `protobuf:"bytes,1,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	Gaze          *Gaze                  `protobuf:"bytes,2,opt,name=gaze,proto3" json:"gaze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestowGazeRequest) Reset() {
	*x = BestowGazeRequest{}
	mi := &file_edict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestowGazeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestowGazeRequest) ProtoMessage() {}

func (x *BestowGazeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestowGazeRequest.ProtoReflect.Descriptor instead.
func (*BestowGazeRequest) Descriptor() ([]byte, []int) {
	return file_edict_proto_rawDescGZIP(), []int{0}
}

func (x *BestowGazeRequest) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

func (x *BestowGazeRequest) GetGaze() *Gaze {
	if x != nil {
		return x.Gaze
	}
	return nil
}

type BestowGazeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Gaze          *Gaze                  `protobuf:"bytes,3,opt,name=gaze,proto3" json:"gaze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestowGazeResponse) Reset() {
	*x = BestowGazeResponse{}
	mi := &file_edict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestowGazeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestowGazeResponse) ProtoMessage() {}

func (x *BestowGazeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestowGazeResponse.ProtoReflect.Descriptor instead.
func (*BestowGazeResponse) Descriptor() ([]byte, []int) {
	return file_edict_proto_rawDescGZIP(), []int{1}
}

func (x *BestowGazeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BestowGazeResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BestowGazeResponse) GetGaze() *Gaze {
	if x != nil {
		return x.Gaze
	}
	return nil
}

var File_edict_proto protoreflect.FileDescriptor

const file_edict_proto_rawDesc = "" +
	"\n" +
	"\vedict.proto\x12\bpanoptes\x1a\fmythos.proto\"N\n" +
	"\x11BestowGazeRequest\x12\x15\n" +
	"\x06eye_id\x18\x01 \x01(\tR\x05eyeId\x12\"\n" +
	"\x04gaze\x18\x02 \x01(\v2\x0e.panoptes.GazeR\x04gaze\"y\n" +
	"\x12BestowGazeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\"\n" +
	"\x04gaze\x18\x03 \x01(\v2\x0e.panoptes.GazeR\x04gaze2a\n" +
	"\x16PanopticonEdictService\x12G\n" +
	"\n" +
	"BestowGaze\x12\x1b.panoptes.BestowGazeRequest\x1a\x1c.panoptes.BestowGazeResponseB%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_edict_proto_rawDescOnce sync.Once
	file_edict_proto_rawDescData []byte
)

func file_edict_proto_rawDescGZIP() []byte {
	file_edict_proto_rawDescOnce.Do(func() {
		file_edict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edict_proto_rawDesc), len(file_edict_proto_rawDesc)))
	})
	return file_edict_proto_rawDescData
}

var file_edict_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_edict_proto_goTypes = []any{
	(*BestowGazeRequest)(nil),  // 0: panoptes.BestowGazeRequest
	(*BestowGazeResponse)(nil), // 1: panoptes.BestowGazeResponse
	(*Gaze)(nil),               // 2: panoptes.Gaze
}
var file_edict_proto_depIdxs = []int32{
	2, // 0: panoptes.BestowGazeRequest.gaze:type_name -> panoptes.Gaze
	2, // 1: panoptes.BestowGazeResponse.gaze:type_name -> panoptes.Gaze
	0, // 2: panoptes.PanopticonEdictService.BestowGaze:input_type -> panoptes.BestowGazeRequest
	1, // 3: panoptes.PanopticonEdictService.BestowGaze:output_type -> panoptes.BestowGazeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_edict_proto_init() }
func file_edict_proto_init() {
	if File_edict_proto != nil {
		return
	}
	file_mythos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edict_proto_rawDesc), len(file_edict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edict_proto_goTypes,
		DependencyIndexes: file_edict_proto_depIdxs,
		MessageInfos:      file_edict_proto_msgTypes,
	}.Build()
	File_edict_proto = out.File
	file_edict_proto_goTypes = nil
	file_edict_proto_depIdxs = nil
}
