// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: edict.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PanopticonEdictService_BestowGaze_FullMethodName      = "/panoptes.PanopticonEdictService/BestowGaze"
	PanopticonEdictService_ForgeOracleSeal_FullMethodName = "/panoptes.PanopticonEdictService/ForgeOracleSeal"
)

// PanopticonEdictServiceClient is the client API for PanopticonEdictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanopticonEdictServiceClient interface {
	BestowGaze(ctx context.Context, in *BestowGazeRequest, opts ...grpc.CallOption) (*BestowGazeResponse, error)
	ForgeOracleSeal(ctx context.Context, in *ForgeOracleSealRequest, opts ...grpc.CallOption) (*ForgeOracleSealResponse, error)
}

type panopticonEdictServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanopticonEdictServiceClient(cc grpc.ClientConnInterface) PanopticonEdictServiceClient {
	return &panopticonEdictServiceClient{cc}
}

func (c *panopticonEdictServiceClient) BestowGaze(ctx context.Context, in *BestowGazeRequest, opts ...grpc.CallOption) (*BestowGazeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BestowGazeResponse)
	err := c.cc.Invoke(ctx, PanopticonEdictService_BestowGaze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panopticonEdictServiceClient) ForgeOracleSeal(ctx context.Context, in *ForgeOracleSealRequest, opts ...grpc.CallOption) (*ForgeOracleSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgeOracleSealResponse)
	err := c.cc.Invoke(ctx, PanopticonEdictService_ForgeOracleSeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanopticonEdictServiceServer is the server API for PanopticonEdictService service.
// All implementations must embed UnimplementedPanopticonEdictServiceServer
// for forward compatibility.
type PanopticonEdictServiceServer interface {
	BestowGaze(context.Context, *BestowGazeRequest) (*BestowGazeResponse, error)
	ForgeOracleSeal(context.Context, *ForgeOracleSealRequest) (*ForgeOracleSealResponse, error)
	mustEmbedUnimplementedPanopticonEdictServiceServer()
}

// UnimplementedPanopticonEdictServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanopticonEdictServiceServer struct{}

func (UnimplementedPanopticonEdictServiceServer) BestowGaze(context.Context, *BestowGazeRequest) (*BestowGazeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BestowGaze not implemented")
}
func (UnimplementedPanopticonEdictServiceServer) ForgeOracleSeal(context.Context, *ForgeOracleSealRequest) (*ForgeOracleSealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgeOracleSeal not implemented")
}
func (UnimplementedPanopticonEdictServiceServer) mustEmbedUnimplementedPanopticonEdictServiceServer() {
}
func (UnimplementedPanopticonEdictServiceServer) testEmbeddedByValue() {}

// UnsafePanopticonEdictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanopticonEdictServiceServer will
// result in compilation errors.
type UnsafePanopticonEdictServiceServer interface {
	mustEmbedUnimplementedPanopticonEdictServiceServer()
}

func RegisterPanopticonEdictServiceServer(s grpc.ServiceRegistrar, srv PanopticonEdictServiceServer) {
	// If the following call panics, it indicates UnimplementedPanopticonEdictServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PanopticonEdictService_ServiceDesc, srv)
}

func _PanopticonEdictService_BestowGaze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BestowGazeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanopticonEdictServiceServer).BestowGaze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanopticonEdictService_BestowGaze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanopticonEdictServiceServer).BestowGaze(ctx, req.(*BestowGazeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PanopticonEdictService_ForgeOracleSeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgeOracleSealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanopticonEdictServiceServer).ForgeOracleSeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanopticonEdictService_ForgeOracleSeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanopticonEdictServiceServer).ForgeOracleSeal(ctx, req.(*ForgeOracleSealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PanopticonEdictService_ServiceDesc is the grpc.ServiceDesc for PanopticonEdictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanopticonEdictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panoptes.PanopticonEdictService",
	HandlerType: (*PanopticonEdictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BestowGaze",
			Handler:    _PanopticonEdictService_BestowGaze_Handler,
		},
		{
			MethodName: "ForgeOracleSeal",
			Handler:    _PanopticonEdictService_ForgeOracleSeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edict.proto",
}
