// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mythos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vision        string                 `protobuf:"bytes,1,opt,name=vision,proto3" json:"vision,omitempty"`
	Form          uint32                 `protobuf:"varint,2,opt,name=form,proto3" json:"form,omitempty"`
	Awake         bool                   `protobuf:"varint,3,opt,name=awake,proto3" json:"awake,omitempty"`
	SlumberReason string                 `protobuf:"bytes,4,opt,name=slumber_reason,json=slumberReason,proto3" json:"slumber_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vision) Reset() {
	*x = Vision{}
	mi := &file_mythos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vision) ProtoMessage() {}

func (x *Vision) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vision.ProtoReflect.Descriptor instead.
func (*Vision) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{0}
}

func (x *Vision) GetVision() string {
	if x != nil {
		return x.Vision
	}
	return ""
}

func (x *Vision) GetForm() uint32 {
	if x != nil {
		return x.Form
	}
	return 0
}

func (x *Vision) GetAwake() bool {
	if x != nil {
		return x.Awake
	}
	return false
}

func (x *Vision) GetSlumberReason() string {
	if x != nil {
		return x.SlumberReason
	}
	return ""
}

type Gaze struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigil         string                 `protobuf:"bytes,1,opt,name=sigil,proto3" json:"sigil,omitempty"`
	Turn          uint64                 `protobuf:"varint,2,opt,name=turn,proto3" json:"turn,omitempty"`
	Awake         bool                   `protobuf:"varint,3,opt,name=awake,proto3" json:"awake,omitempty"`
	Vision        string                 `protobuf:"bytes,4,opt,name=vision,proto3" json:"vision,omitempty"`
	Form          uint32                 `protobuf:"varint,5,opt,name=form,proto3" json:"form,omitempty"`
	Focus         *structpb.Struct       `protobuf:"bytes,6,opt,name=focus,proto3" json:"focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gaze) Reset() {
	*x = Gaze{}
	mi := &file_mythos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gaze) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gaze) ProtoMessage() {}

func (x *Gaze) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gaze.ProtoReflect.Descriptor instead.
func (*Gaze) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{1}
}

func (x *Gaze) GetSigil() string {
	if x != nil {
		return x.Sigil
	}
	return ""
}

func (x *Gaze) GetTurn() uint64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Gaze) GetAwake() bool {
	if x != nil {
		return x.Awake
	}
	return false
}

func (x *Gaze) GetVision() string {
	if x != nil {
		return x.Vision
	}
	return ""
}

func (x *Gaze) GetForm() uint32 {
	if x != nil {
		return x.Form
	}
	return 0
}

func (x *Gaze) GetFocus() *structpb.Struct {
	if x != nil {
		return x.Focus
	}
	return nil
}

var File_mythos_proto protoreflect.FileDescriptor

const file_mythos_proto_rawDesc = "" +
	"\n" +
	"\fmythos.proto\x12\bpanoptes\x1a\x1cgoogle/protobuf/struct.proto\"q\n" +
	"\x06Vision\x12\x16\n" +
	"\x06vision\x18\x01 \x01(\tR\x06vision\x12\x12\n" +
	"\x04form\x18\x02 \x01(\rR\x04form\x12\x14\n" +
	"\x05awake\x18\x03 \x01(\bR\x05awake\x12%\n" +
	"\x0eslumber_reason\x18\x04 \x01(\tR\rslumberReason\"\xa1\x01\n" +
	"\x04Gaze\x12\x14\n" +
	"\x05sigil\x18\x01 \x01(\tR\x05sigil\x12\x12\n" +
	"\x04turn\x18\x02 \x01(\x04R\x04turn\x12\x14\n" +
	"\x05awake\x18\x03 \x01(\bR\x05awake\x12\x16\n" +
	"\x06vision\x18\x04 \x01(\tR\x06vision\x12\x12\n" +
	"\x04form\x18\x05 \x01(\rR\x04form\x12-\n" +
	"\x05focus\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05focusB%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_mythos_proto_rawDescOnce sync.Once
	file_mythos_proto_rawDescData []byte
)

func file_mythos_proto_rawDescGZIP() []byte {
	file_mythos_proto_rawDescOnce.Do(func() {
		file_mythos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mythos_proto_rawDesc), len(file_mythos_proto_rawDesc)))
	})
	return file_mythos_proto_rawDescData
}

var file_mythos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mythos_proto_goTypes = []any{
	(*Vision)(nil),          // 0: panoptes.Vision
	(*Gaze)(nil),            // 1: panoptes.Gaze
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_mythos_proto_depIdxs = []int32{
	2, // 0: panoptes.Gaze.focus:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mythos_proto_init() }
func file_mythos_proto_init() {
	if File_mythos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mythos_proto_rawDesc), len(file_mythos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mythos_proto_goTypes,
		DependencyIndexes: file_mythos_proto_depIdxs,
		MessageInfos:      file_mythos_proto_msgTypes,
	}.Build()
	File_mythos_proto = out.File
	file_mythos_proto_goTypes = nil
	file_mythos_proto_depIdxs = nil
}
