// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/mythos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PanoptesService_BindEye_FullMethodName = "/panoptes.PanoptesService/BindEye"
)

// PanoptesServiceClient is the client API for PanoptesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanoptesServiceClient interface {
	BindEye(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
}

type panoptesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanoptesServiceClient(cc grpc.ClientConnInterface) PanoptesServiceClient {
	return &panoptesServiceClient{cc}
}

func (c *panoptesServiceClient) BindEye(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindResponse)
	err := c.cc.Invoke(ctx, PanoptesService_BindEye_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanoptesServiceServer is the server API for PanoptesService service.
// All implementations must embed UnimplementedPanoptesServiceServer
// for forward compatibility.
type PanoptesServiceServer interface {
	BindEye(context.Context, *BindRequest) (*BindResponse, error)
	mustEmbedUnimplementedPanoptesServiceServer()
}

// UnimplementedPanoptesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanoptesServiceServer struct{}

func (UnimplementedPanoptesServiceServer) BindEye(context.Context, *BindRequest) (*BindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindEye not implemented")
}
func (UnimplementedPanoptesServiceServer) mustEmbedUnimplementedPanoptesServiceServer() {}
func (UnimplementedPanoptesServiceServer) testEmbeddedByValue()                         {}

// UnsafePanoptesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanoptesServiceServer will
// result in compilation errors.
type UnsafePanoptesServiceServer interface {
	mustEmbedUnimplementedPanoptesServiceServer()
}

func RegisterPanoptesServiceServer(s grpc.ServiceRegistrar, srv PanoptesServiceServer) {
	// If the following call panics, it indicates UnimplementedPanoptesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PanoptesService_ServiceDesc, srv)
}

func _PanoptesService_BindEye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanoptesServiceServer).BindEye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanoptesService_BindEye_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanoptesServiceServer).BindEye(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PanoptesService_ServiceDesc is the grpc.ServiceDesc for PanoptesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanoptesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panoptes.PanoptesService",
	HandlerType: (*PanoptesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindEye",
			Handler:    _PanoptesService_BindEye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mythos.proto",
}
