// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/mythos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EyeId         string                 `protobuf:"bytes,1,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_proto_mythos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mythos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_proto_mythos_proto_rawDescGZIP(), []int{0}
}

func (x *BindRequest) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_proto_mythos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mythos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_proto_mythos_proto_rawDescGZIP(), []int{1}
}

func (x *BindResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_proto_mythos_proto protoreflect.FileDescriptor

const file_proto_mythos_proto_rawDesc = "" +
	"\n" +
	"\x12proto/mythos.proto\x12\bpanoptes\"$\n" +
	"\vBindRequest\x12\x15\n" +
	"\x06eye_id\x18\x01 \x01(\tR\x05eyeId\"O\n" +
	"\fBindResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage2K\n" +
	"\x0fPanoptesService\x128\n" +
	"\aBindEye\x12\x15.panoptes.BindRequest\x1a\x16.panoptes.BindResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_mythos_proto_rawDescOnce sync.Once
	file_proto_mythos_proto_rawDescData []byte
)

func file_proto_mythos_proto_rawDescGZIP() []byte {
	file_proto_mythos_proto_rawDescOnce.Do(func() {
		file_proto_mythos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mythos_proto_rawDesc), len(file_proto_mythos_proto_rawDesc)))
	})
	return file_proto_mythos_proto_rawDescData
}

var file_proto_mythos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mythos_proto_goTypes = []any{
	(*BindRequest)(nil),  // 0: panoptes.BindRequest
	(*BindResponse)(nil), // 1: panoptes.BindResponse
}
var file_proto_mythos_proto_depIdxs = []int32{
	0, // 0: panoptes.PanoptesService.BindEye:input_type -> panoptes.BindRequest
	1, // 1: panoptes.PanoptesService.BindEye:output_type -> panoptes.BindResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mythos_proto_init() }
func file_proto_mythos_proto_init() {
	if File_proto_mythos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mythos_proto_rawDesc), len(file_proto_mythos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mythos_proto_goTypes,
		DependencyIndexes: file_proto_mythos_proto_depIdxs,
		MessageInfos:      file_proto_mythos_proto_msgTypes,
	}.Build()
	File_proto_mythos_proto = out.File
	file_proto_mythos_proto_goTypes = nil
	file_proto_mythos_proto_depIdxs = nil
}
