// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mythos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EyeId         string                 `protobuf:"bytes,1,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_mythos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{0}
}

func (x *BindRequest) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_mythos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{1}
}

func (x *BindResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type EyePulse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EyeId         string                 `protobuf:"bytes,1,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,2,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EyePulse) Reset() {
	*x = EyePulse{}
	mi := &file_mythos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EyePulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EyePulse) ProtoMessage() {}

func (x *EyePulse) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EyePulse.ProtoReflect.Descriptor instead.
func (*EyePulse) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{2}
}

func (x *EyePulse) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

func (x *EyePulse) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

type PanopticonSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanopticonSignal) Reset() {
	*x = PanopticonSignal{}
	mi := &file_mythos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanopticonSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanopticonSignal) ProtoMessage() {}

func (x *PanopticonSignal) ProtoReflect() protoreflect.Message {
	mi := &file_mythos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanopticonSignal.ProtoReflect.Descriptor instead.
func (*PanopticonSignal) Descriptor() ([]byte, []int) {
	return file_mythos_proto_rawDescGZIP(), []int{3}
}

func (x *PanopticonSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mythos_proto protoreflect.FileDescriptor

const file_mythos_proto_rawDesc = "" +
	"\n" +
	"\fmythos.proto\x12\bpanoptes\"$\n" +
	"\vBindRequest\x12\x15\n" +
	"\x06eye_id\x18\x01 \x01(\tR\x05eyeId\"O\n" +
	"\fBindResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"C\n" +
	"\bEyePulse\x12\x15\n" +
	"\x06eye_id\x18\x01 \x01(\tR\x05eyeId\x12 \n" +
	"\fsent_at_unix\x18\x02 \x01(\x03R\n" +
	"sentAtUnix\",\n" +
	"\x10PanopticonSignal\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8c\x01\n" +
	"\x0fPanoptesService\x128\n" +
	"\aBindEye\x12\x15.panoptes.BindRequest\x1a\x16.panoptes.BindResponse\x12?\n" +
	"\tKeepVigil\x12\x12.panoptes.EyePulse\x1a\x1a.panoptes.PanopticonSignal(\x010\x01B%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_mythos_proto_rawDescOnce sync.Once
	file_mythos_proto_rawDescData []byte
)

func file_mythos_proto_rawDescGZIP() []byte {
	file_mythos_proto_rawDescOnce.Do(func() {
		file_mythos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mythos_proto_rawDesc), len(file_mythos_proto_rawDesc)))
	})
	return file_mythos_proto_rawDescData
}

var file_mythos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mythos_proto_goTypes = []any{
	(*BindRequest)(nil),      // 0: panoptes.BindRequest
	(*BindResponse)(nil),     // 1: panoptes.BindResponse
	(*EyePulse)(nil),         // 2: panoptes.EyePulse
	(*PanopticonSignal)(nil), // 3: panoptes.PanopticonSignal
}
var file_mythos_proto_depIdxs = []int32{
	0, // 0: panoptes.PanoptesService.BindEye:input_type -> panoptes.BindRequest
	2, // 1: panoptes.PanoptesService.KeepVigil:input_type -> panoptes.EyePulse
	1, // 2: panoptes.PanoptesService.BindEye:output_type -> panoptes.BindResponse
	3, // 3: panoptes.PanoptesService.KeepVigil:output_type -> panoptes.PanopticonSignal
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mythos_proto_init() }
func file_mythos_proto_init() {
	if File_mythos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mythos_proto_rawDesc), len(file_mythos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mythos_proto_goTypes,
		DependencyIndexes: file_mythos_proto_depIdxs,
		MessageInfos:      file_mythos_proto_msgTypes,
	}.Build()
	File_mythos_proto = out.File
	file_mythos_proto_goTypes = nil
	file_mythos_proto_depIdxs = nil
}
