// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: omen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Omen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OmenId         string                 `protobuf:"bytes,1,opt,name=omen_id,json=omenId,proto3" json:"omen_id,omitempty"`
	EyeId          string                 `protobuf:"bytes,2,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	GazeSigil      string                 `protobuf:"bytes,4,opt,name=gaze_sigil,json=gazeSigil,proto3" json:"gaze_sigil,omitempty"`
	GazeTurn       uint64                 `protobuf:"varint,5,opt,name=gaze_turn,json=gazeTurn,proto3" json:"gaze_turn,omitempty"`
	BefallenAtUnix int64                  `protobuf:"varint,6,opt,name=befallen_at_unix,json=befallenAtUnix,proto3" json:"befallen_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Omen) Reset() {
	*x = Omen{}
	mi := &file_omen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Omen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Omen) ProtoMessage() {}

func (x *Omen) ProtoReflect() protoreflect.Message {
	mi := &file_omen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Omen.ProtoReflect.Descriptor instead.
func (*Omen) Descriptor() ([]byte, []int) {
	return file_omen_proto_rawDescGZIP(), []int{0}
}

func (x *Omen) GetOmenId() string {
	if x != nil {
		return x.OmenId
	}
	return ""
}

func (x *Omen) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

func (x *Omen) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Omen) GetGazeSigil() string {
	if x != nil {
		return x.GazeSigil
	}
	return ""
}

func (x *Omen) GetGazeTurn() uint64 {
	if x != nil {
		return x.GazeTurn
	}
	return 0
}

func (x *Omen) GetBefallenAtUnix() int64 {
	if x != nil {
		return x.BefallenAtUnix
	}
	return 0
}

type OmenReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmenReceipt) Reset() {
	*x = OmenReceipt{}
	mi := &file_omen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmenReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmenReceipt) ProtoMessage() {}

func (x *OmenReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_omen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmenReceipt.ProtoReflect.Descriptor instead.
func (*OmenReceipt) Descriptor() ([]byte, []int) {
	return file_omen_proto_rawDescGZIP(), []int{1}
}

func (x *OmenReceipt) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *OmenReceipt) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_omen_proto protoreflect.FileDescriptor

const file_omen_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"omen.proto\x12\bpanoptes\"\xb2\x01\n" +
	"\x04Omen\x12\x17\n" +
	"\aomen_id\x18\x01 \x01(\tR\x06omenId\x12\x15\n" +
	"\x06eye_id\x18\x02 \x01(\tR\x05eyeId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x1d\n" +
	"\n" +
	"gaze_sigil\x18\x04 \x01(\tR\tgazeSigil\x12\x1b\n" +
	"\tgaze_turn\x18\x05 \x01(\x04R\bgazeTurn\x12(\n" +
	"\x10befallen_at_unix\x18\x06 \x01(\x03R\x0ebefallenAtUnix\"A\n" +
	"\vOmenReceipt\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2I\n" +
	"\x13PanoptesOmenService\x122\n" +
	"\tRaiseOmen\x12\x0e.panoptes.Omen\x1a\x15.panoptes.OmenReceiptB%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_omen_proto_rawDescOnce sync.Once
	file_omen_proto_rawDescData []byte
)

func file_omen_proto_rawDescGZIP() []byte {
	file_omen_proto_rawDescOnce.Do(func() {
		file_omen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omen_proto_rawDesc), len(file_omen_proto_rawDesc)))
	})
	return file_omen_proto_rawDescData
}

var file_omen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_omen_proto_goTypes = []any{
	(*Omen)(nil),        // 0: panoptes.Omen
	(*OmenReceipt)(nil), // 1: panoptes.OmenReceipt
}
var file_omen_proto_depIdxs = []int32{
	0, // 0: panoptes.PanoptesOmenService.RaiseOmen:input_type -> panoptes.Omen
	1, // 1: panoptes.PanoptesOmenService.RaiseOmen:output_type -> panoptes.OmenReceipt
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_omen_proto_init() }
func file_omen_proto_init() {
	if File_omen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omen_proto_rawDesc), len(file_omen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omen_proto_goTypes,
		DependencyIndexes: file_omen_proto_depIdxs,
		MessageInfos:      file_omen_proto_msgTypes,
	}.Build()
	File_omen_proto = out.File
	file_omen_proto_goTypes = nil
	file_omen_proto_depIdxs = nil
}
