// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: oracle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PanoptesOracleService_PairOracle_FullMethodName         = "/panoptes.PanoptesOracleService/PairOracle"
	PanoptesOracleService_RefreshOracleToken_FullMethodName = "/panoptes.PanoptesOracleService/RefreshOracleToken"
)

// PanoptesOracleServiceClient is the client API for PanoptesOracleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanoptesOracleServiceClient interface {
	PairOracle(ctx context.Context, in *PairOracleRequest, opts ...grpc.CallOption) (*PairOracleResponse, error)
	RefreshOracleToken(ctx context.Context, in *RefreshOracleTokenRequest, opts ...grpc.CallOption) (*RefreshOracleTokenResponse, error)
}

type panoptesOracleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanoptesOracleServiceClient(cc grpc.ClientConnInterface) PanoptesOracleServiceClient {
	return &panoptesOracleServiceClient{cc}
}

func (c *panoptesOracleServiceClient) PairOracle(ctx context.Context, in *PairOracleRequest, opts ...grpc.CallOption) (*PairOracleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairOracleResponse)
	err := c.cc.Invoke(ctx, PanoptesOracleService_PairOracle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panoptesOracleServiceClient) RefreshOracleToken(ctx context.Context, in *RefreshOracleTokenRequest, opts ...grpc.CallOption) (*RefreshOracleTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshOracleTokenResponse)
	err := c.cc.Invoke(ctx, PanoptesOracleService_RefreshOracleToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanoptesOracleServiceServer is the server API for PanoptesOracleService service.
// All implementations must embed UnimplementedPanoptesOracleServiceServer
// for forward compatibility.
type PanoptesOracleServiceServer interface {
	PairOracle(context.Context, *PairOracleRequest) (*PairOracleResponse, error)
	RefreshOracleToken(context.Context, *RefreshOracleTokenRequest) (*RefreshOracleTokenResponse, error)
	mustEmbedUnimplementedPanoptesOracleServiceServer()
}

// UnimplementedPanoptesOracleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanoptesOracleServiceServer struct{}

func (UnimplementedPanoptesOracleServiceServer) PairOracle(context.Context, *PairOracleRequest) (*PairOracleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PairOracle not implemented")
}
func (UnimplementedPanoptesOracleServiceServer) RefreshOracleToken(context.Context, *RefreshOracleTokenRequest) (*RefreshOracleTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshOracleToken not implemented")
}
func (UnimplementedPanoptesOracleServiceServer) mustEmbedUnimplementedPanoptesOracleServiceServer() {}
func (UnimplementedPanoptesOracleServiceServer) testEmbeddedByValue()                               {}

// UnsafePanoptesOracleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanoptesOracleServiceServer will
// result in compilation errors.
type UnsafePanoptesOracleServiceServer interface {
	mustEmbedUnimplementedPanoptesOracleServiceServer()
}

func RegisterPanoptesOracleServiceServer(s grpc.ServiceRegistrar, srv PanoptesOracleServiceServer) {
	// If the following call panics, it indicates UnimplementedPanoptesOracleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PanoptesOracleService_ServiceDesc, srv)
}

func _PanoptesOracleService_PairOracle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairOracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanoptesOracleServiceServer).PairOracle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanoptesOracleService_PairOracle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanoptesOracleServiceServer).PairOracle(ctx, req.(*PairOracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PanoptesOracleService_RefreshOracleToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshOracleTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanoptesOracleServiceServer).RefreshOracleToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanoptesOracleService_RefreshOracleToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanoptesOracleServiceServer).RefreshOracleToken(ctx, req.(*RefreshOracleTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PanoptesOracleService_ServiceDesc is the grpc.ServiceDesc for PanoptesOracleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanoptesOracleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panoptes.PanoptesOracleService",
	HandlerType: (*PanoptesOracleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PairOracle",
			Handler:    _PanoptesOracleService_PairOracle_Handler,
		},
		{
			MethodName: "RefreshOracleToken",
			Handler:    _PanoptesOracleService_RefreshOracleToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}
