// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: oracle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairOracleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleId      string                 `protobuf:"bytes,1,opt,name=oracle_id,json=oracleId,proto3" json:"oracle_id,omitempty"`
	OracleSeal    string                 `protobuf:"bytes,2,opt,name=oracle_seal,json=oracleSeal,proto3" json:"oracle_seal,omitempty"`
	FcmToken      string                 `protobuf:"bytes,3,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairOracleRequest) Reset() {
	*x = PairOracleRequest{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairOracleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairOracleRequest) ProtoMessage() {}

func (x *PairOracleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairOracleRequest.ProtoReflect.Descriptor instead.
func (*PairOracleRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *PairOracleRequest) GetOracleId() string {
	if x != nil {
		return x.OracleId
	}
	return ""
}

func (x *PairOracleRequest) GetOracleSeal() string {
	if x != nil {
		return x.OracleSeal
	}
	return ""
}

func (x *PairOracleRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

type PairOracleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	OracleBrand   string                 `protobuf:"bytes,3,opt,name=oracle_brand,json=oracleBrand,proto3" json:"oracle_brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairOracleResponse) Reset() {
	*x = PairOracleResponse{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairOracleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairOracleResponse) ProtoMessage() {}

func (x *PairOracleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairOracleResponse.ProtoReflect.Descriptor instead.
func (*PairOracleResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *PairOracleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PairOracleResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *PairOracleResponse) GetOracleBrand() string {
	if x != nil {
		return x.OracleBrand
	}
	return ""
}

type RefreshOracleTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleId      string                 `protobuf:"bytes,1,opt,name=oracle_id,json=oracleId,proto3" json:"oracle_id,omitempty"`
	OracleBrand   string                 `protobuf:"bytes,2,opt,name=oracle_brand,json=oracleBrand,proto3" json:"oracle_brand,omitempty"`
	FcmToken      string                 `protobuf:"bytes,3,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshOracleTokenRequest) Reset() {
	*x = RefreshOracleTokenRequest{}
	mi := &file_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshOracleTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshOracleTokenRequest) ProtoMessage() {}

func (x *RefreshOracleTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshOracleTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshOracleTokenRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshOracleTokenRequest) GetOracleId() string {
	if x != nil {
		return x.OracleId
	}
	return ""
}

func (x *RefreshOracleTokenRequest) GetOracleBrand() string {
	if x != nil {
		return x.OracleBrand
	}
	return ""
}

func (x *RefreshOracleTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

type RefreshOracleTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshOracleTokenResponse) Reset() {
	*x = RefreshOracleTokenResponse{}
	mi := &file_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshOracleTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshOracleTokenResponse) ProtoMessage() {}

func (x *RefreshOracleTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshOracleTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshOracleTokenResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshOracleTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshOracleTokenResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\bpanoptes\"n\n" +
	"\x11PairOracleRequest\x12\x1b\n" +
	"\toracle_id\x18\x01 \x01(\tR\boracleId\x12\x1f\n" +
	"\voracle_seal\x18\x02 \x01(\tR\n" +
	"oracleSeal\x12\x1b\n" +
	"\tfcm_token\x18\x03 \x01(\tR\bfcmToken\"x\n" +
	"\x12PairOracleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12!\n" +
	"\foracle_brand\x18\x03 \x01(\tR\voracleBrand\"x\n" +
	"\x19RefreshOracleTokenRequest\x12\x1b\n" +
	"\toracle_id\x18\x01 \x01(\tR\boracleId\x12!\n" +
	"\foracle_brand\x18\x02 \x01(\tR\voracleBrand\x12\x1b\n" +
	"\tfcm_token\x18\x03 \x01(\tR\bfcmToken\"]\n" +
	"\x1aRefreshOracleTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage2\xc1\x01\n" +
	"\x15PanoptesOracleService\x12G\n" +
	"\n" +
	"PairOracle\x12\x1b.panoptes.PairOracleRequest\x1a\x1c.panoptes.PairOracleResponse\x12_\n" +
	"\x12RefreshOracleToken\x12#.panoptes.RefreshOracleTokenRequest\x1a$.panoptes.RefreshOracleTokenResponseB%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_oracle_proto_goTypes = []any{
	(*PairOracleRequest)(nil),          // 0: panoptes.PairOracleRequest
	(*PairOracleResponse)(nil),         // 1: panoptes.PairOracleResponse
	(*RefreshOracleTokenRequest)(nil),  // 2: panoptes.RefreshOracleTokenRequest
	(*RefreshOracleTokenResponse)(nil), // 3: panoptes.RefreshOracleTokenResponse
}
var file_oracle_proto_depIdxs = []int32{
	0, // 0: panoptes.PanoptesOracleService.PairOracle:input_type -> panoptes.PairOracleRequest
	2, // 1: panoptes.PanoptesOracleService.RefreshOracleToken:input_type -> panoptes.RefreshOracleTokenRequest
	1, // 2: panoptes.PanoptesOracleService.PairOracle:output_type -> panoptes.PairOracleResponse
	3, // 3: panoptes.PanoptesOracleService.RefreshOracleToken:output_type -> panoptes.RefreshOracleTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
