// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: panoptes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_panoptes_proto protoreflect.FileDescriptor

const file_panoptes_proto_rawDesc = "" +
	"\n" +
	"\x0epanoptes.proto\x12\bpanoptes\x1a\rbinding.proto\x1a\vvigil.proto2\x8c\x01\n" +
	"\x0fPanoptesService\x128\n" +
	"\aBindEye\x12\x15.panoptes.BindRequest\x1a\x16.panoptes.BindResponse\x12?\n" +
	"\tKeepVigil\x12\x12.panoptes.EyePulse\x1a\x1a.panoptes.PanopticonSignal(\x010\x01B%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var file_panoptes_proto_goTypes = []any{
	(*BindRequest)(nil),      // 0: panoptes.BindRequest
	(*EyePulse)(nil),         // 1: panoptes.EyePulse
	(*BindResponse)(nil),     // 2: panoptes.BindResponse
	(*PanopticonSignal)(nil), // 3: panoptes.PanopticonSignal
}
var file_panoptes_proto_depIdxs = []int32{
	0, // 0: panoptes.PanoptesService.BindEye:input_type -> panoptes.BindRequest
	1, // 1: panoptes.PanoptesService.KeepVigil:input_type -> panoptes.EyePulse
	2, // 2: panoptes.PanoptesService.BindEye:output_type -> panoptes.BindResponse
	3, // 3: panoptes.PanoptesService.KeepVigil:output_type -> panoptes.PanopticonSignal
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_panoptes_proto_init() }
func file_panoptes_proto_init() {
	if File_panoptes_proto != nil {
		return
	}
	file_binding_proto_init()
	file_vigil_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panoptes_proto_rawDesc), len(file_panoptes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panoptes_proto_goTypes,
		DependencyIndexes: file_panoptes_proto_depIdxs,
	}.Build()
	File_panoptes_proto = out.File
	file_panoptes_proto_goTypes = nil
	file_panoptes_proto_depIdxs = nil
}
