// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: vigil.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EyePulse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EyeId         string                 `protobuf:"bytes,1,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,2,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EyePulse) Reset() {
	*x = EyePulse{}
	mi := &file_vigil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EyePulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EyePulse) ProtoMessage() {}

func (x *EyePulse) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EyePulse.ProtoReflect.Descriptor instead.
func (*EyePulse) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{0}
}

func (x *EyePulse) GetEyeId() string {
	if x != nil {
		return x.EyeId
	}
	return ""
}

func (x *EyePulse) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *EyePulse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type PanopticonSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Gaze          *Gaze                  `protobuf:"bytes,2,opt,name=gaze,proto3" json:"gaze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanopticonSignal) Reset() {
	*x = PanopticonSignal{}
	mi := &file_vigil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanopticonSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanopticonSignal) ProtoMessage() {}

func (x *PanopticonSignal) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanopticonSignal.ProtoReflect.Descriptor instead.
func (*PanopticonSignal) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{1}
}

func (x *PanopticonSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PanopticonSignal) GetGaze() *Gaze {
	if x != nil {
		return x.Gaze
	}
	return nil
}

var File_vigil_proto protoreflect.FileDescriptor

const file_vigil_proto_rawDesc = "" +
	"\n" +
	"\vvigil.proto\x12\bpanoptes\x1a\fmythos.proto\"Y\n" +
	"\bEyePulse\x12\x15\n" +
	"\x06eye_id\x18\x01 \x01(\tR\x05eyeId\x12 \n" +
	"\fsent_at_unix\x18\x02 \x01(\x03R\n" +
	"sentAtUnix\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\"P\n" +
	"\x10PanopticonSignal\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\"\n" +
	"\x04gaze\x18\x02 \x01(\v2\x0e.panoptes.GazeR\x04gazeB%Z#github.com/Kirragami/panoptes/protob\x06proto3"

var (
	file_vigil_proto_rawDescOnce sync.Once
	file_vigil_proto_rawDescData []byte
)

func file_vigil_proto_rawDescGZIP() []byte {
	file_vigil_proto_rawDescOnce.Do(func() {
		file_vigil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vigil_proto_rawDesc), len(file_vigil_proto_rawDesc)))
	})
	return file_vigil_proto_rawDescData
}

var file_vigil_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vigil_proto_goTypes = []any{
	(*EyePulse)(nil),         // 0: panoptes.EyePulse
	(*PanopticonSignal)(nil), // 1: panoptes.PanopticonSignal
	(*Gaze)(nil),             // 2: panoptes.Gaze
}
var file_vigil_proto_depIdxs = []int32{
	2, // 0: panoptes.PanopticonSignal.gaze:type_name -> panoptes.Gaze
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vigil_proto_init() }
func file_vigil_proto_init() {
	if File_vigil_proto != nil {
		return
	}
	file_mythos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vigil_proto_rawDesc), len(file_vigil_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vigil_proto_goTypes,
		DependencyIndexes: file_vigil_proto_depIdxs,
		MessageInfos:      file_vigil_proto_msgTypes,
	}.Build()
	File_vigil_proto = out.File
	file_vigil_proto_goTypes = nil
	file_vigil_proto_depIdxs = nil
}
